/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package information;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author renata
 */
public class VasosDados extends javax.swing.JFrame {

    /**
     * Creates new form VasosDados
     */
    public VasosDados() {
        initComponents();
        ifPainel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnU = new javax.swing.JButton();
        ifPainel = new javax.swing.JInternalFrame();
        jLabel2 = new javax.swing.JLabel();
        lblRESO1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblIDI = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblHOR = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblUSU = new javax.swing.JLabel();
        lblRESO2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblPC = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Informer");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Suas informações do seu PC");

        btnU.setForeground(new java.awt.Color(51, 255, 0));
        btnU.setText("HELLO");
        btnU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUActionPerformed(evt);
            }
        });

        ifPainel.setVisible(true);

        jLabel2.setText("Resolução: ");

        lblRESO1.setForeground(new java.awt.Color(255, 255, 0));
        lblRESO1.setText("0");

        jLabel4.setText("Idioma:");

        lblIDI.setForeground(new java.awt.Color(0, 0, 255));
        lblIDI.setText("I");

        jLabel6.setText("Hora: ");

        lblHOR.setForeground(new java.awt.Color(255, 0, 255));
        lblHOR.setText("O");

        jLabel8.setText("Nome do usuário:");

        lblUSU.setForeground(new java.awt.Color(102, 255, 204));
        lblUSU.setText("U");

        lblRESO2.setForeground(new java.awt.Color(255, 255, 0));
        lblRESO2.setText("0");

        jLabel3.setText("Nome do pc:");

        lblPC.setForeground(new java.awt.Color(153, 0, 0));
        lblPC.setText("PC");

        javax.swing.GroupLayout ifPainelLayout = new javax.swing.GroupLayout(ifPainel.getContentPane());
        ifPainel.getContentPane().setLayout(ifPainelLayout);
        ifPainelLayout.setHorizontalGroup(
            ifPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ifPainelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ifPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ifPainelLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(lblUSU))
                    .addGroup(ifPainelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(lblPC))
                    .addGroup(ifPainelLayout.createSequentialGroup()
                        .addGroup(ifPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ifPainelLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblHOR))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ifPainelLayout.createSequentialGroup()
                                .addGroup(ifPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(ifPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblIDI)
                                    .addComponent(lblRESO1))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRESO2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ifPainelLayout.setVerticalGroup(
            ifPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ifPainelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ifPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblRESO1)
                    .addComponent(lblRESO2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ifPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblIDI))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ifPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblHOR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ifPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblUSU))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ifPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblPC))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ifPainel, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(btnU)))
                .addContainerGap(162, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnU)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ifPainel))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUActionPerformed
        ifPainel.setVisible(true);

        // Resolução do pc
        Toolkit tk = Toolkit.getDefaultToolkit(); 
        Dimension d = tk.getScreenSize();
        
        lblRESO1.setText("largura: " + d.width);
        lblRESO2.setText("altura: " + d.height);
        //Idioma do pc
        Locale loc = Locale.getDefault();
        lblIDI.setText(loc.getDisplayLanguage());
        
        //HORA
        Date hora = new Date();
        lblHOR.setText(hora.toString());
        
        //Nome do usuário
        try {
            lblPC.setText(InetAddress.getLocalHost().getHostName());
        } catch (UnknownHostException ex) {
            Logger.getLogger(VasosDados.class.getName()).log(Level.SEVERE, null, ex);
        }
        String name;
        name = System.getProperty("user.name");
        lblUSU.setText(name);
    }//GEN-LAST:event_btnUActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VasosDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VasosDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VasosDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VasosDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VasosDados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnU;
    private javax.swing.JInternalFrame ifPainel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblHOR;
    private javax.swing.JLabel lblIDI;
    private javax.swing.JLabel lblPC;
    private javax.swing.JLabel lblRESO1;
    private javax.swing.JLabel lblRESO2;
    private javax.swing.JLabel lblUSU;
    // End of variables declaration//GEN-END:variables
}
