/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Jogo;

/**
 *
 * @author renata
 */
public class JogoJframe extends javax.swing.JFrame {

    /**
     * Creates new form JogoJframe
     */
    public JogoJframe() {
        initComponents();
        lblRES.setText("<html>Vou pensar em um valor de <br>1 a 5,tente adivinhar qual valor é</html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRES = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNUM = new javax.swing.JSpinner();
        btnPAL = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jogo_de_adivinhação");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRES.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblRES.setText("Frase");
        lblRES.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(lblRES, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 200, 120));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/KI.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, -20, 320, 240));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/genio.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, -1, -1));

        jLabel4.setText("Valor");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        txtNUM.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        getContentPane().add(txtNUM, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 50, -1));

        btnPAL.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnPAL.setText("PALPITE");
        btnPAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPALActionPerformed(evt);
            }
        });
        getContentPane().add(btnPAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPALActionPerformed
        double value = 1 + Math.random() * (5 - 1);
        int n1 = (int) value;
        int digit = Integer.parseInt(txtNUM.getValue().toString());
        String res1 = "ACERTOU!!";
        String res2 = "ERROU!! Eu pensei no valor " + n1;
        String frase = (n1 == digit)?res1:res2;
        lblRES.setText(frase);
    }//GEN-LAST:event_btnPALActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JogoJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JogoJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JogoJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JogoJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JogoJframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPAL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblRES;
    private javax.swing.JSpinner txtNUM;
    // End of variables declaration//GEN-END:variables
}
